--- 
name: reapsnapshot
description: "Given an aap-awscf-pipeline snapshot, reap all AWS resources associated with it"
inputs: 
  aws_access_key_id: 
    default: ""
    description: "AWS access key ID"
    required: true
  aws_profile: 
    default: aws-acm-dev10
    description: "AWS profile"
    required: true
  aws_secret_access_key: 
    default: ""
    description: "AWS secret access key"
    required: true
  snapshot_path: 
    default: "artifacts/snapshots/SNAPSHOT-2021-08-01-19-23-28"
    description: "Path to snapshot to reap"
    required: true
outputs: 
  snaps: 
    description: "JSON list of reaped resources"
runs: 
  image: Dockerfile
  using: docker
