--- 
name: reapsnapshot
description: "Given an aap-awscf-pipeline snapshot, reap all AWS resources associated with it"
inputs: 
  aws_access_key_id: 
    default: ""
    description: "AWS access key ID"
    required: true
  aws_region: 
    default: 'us-east-2'
    description: "Default AWS region to address"
    required: true
  aws_secret_access_key: 
    default: ""
    description: "AWS secret access key"
    required: true
  snapshot_path: 
    default: "artifacts/snapshots/SNAPSHOT-2021-08-01-19-23-28"
    description: "Path to snapshot to reap"
    required: true
  snapshot_date: 
    default: "2021-08-01-19-23-28"
    description: "Just the date portion of the snapshot"
    required: true
  log_filename:
    default: "reaper.log"
    required: false
  resources_filename:
    default: "resources.json"
    required: false
  dry_run:
    description: 'Report only the resources to be reaped.  If unchecked, deletion will also occur.'
    required: false
    default: false
    type: boolean

outputs: 
  log: 
    description: "Transcript of reaping actions"
runs: 
  image: Dockerfile
  using: docker
