name: Lint

on: [ pull_request, workflow_dispatch ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checks-out under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      - name: Install tox
        run: pip install tox

      - name: Run linters
        run: tox -e linters
